- name: getting package facts
  package_facts:
    manager: auto

- name: copy repos
  become: true
  copy:
    src: files/{{ item }}.repo
    dest: /etc/yum.repos.d/{{ item }}.repo
  with_items:
    - docker-ce
    - hashicorp

- name: epel release
  become: true
  package:
    name:
      - epel-release

- name: libs
  become: true
  package:
    update_cache: yes
    state: present
    name:
      - dnf-plugins-core
      - htop
      - curl
      - nano
      - bind-utils
      - net-tools

- name: update vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.conf