- name: update consul
  become: true
  serial: 1
  hosts: consul_server,nomad_server,worker
  tasks:

  - name: able upgrade
    ansible.builtin.dpkg_selections:
      name: consul
      selection: install

  - name: install consul
    become: true
    package:
      state: present
      name:
        - "{{consul_lib}}"

  - name: Restart consul
    systemd:
      name: consul
      state: restarted
      daemon_reload: yes
      enabled: yes

  - name: disable upgrade
    ansible.builtin.dpkg_selections:
      name: consul
      selection: hold
