---
- name: create paths
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - /root/jobs

- name: copy files
  notify: deploy jobs
  with_fileglob:
    - "files/*"
  copy:
    src: "{{ item }}"
    dest: /root/jobs/
