{
 "title": "Nomad Autoscaler Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(nomad_client_host_memory_used{host=\"metrics-1\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(nomad_client_host_cpu_total{host=\"metrics-1\"})"
    }
   ]
  },
  {
   "title": "Client memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nomad_client_host_memory_total{host=\"metrics-1\"}",
     "legendFormat": "total"
    },
    {
     "expr": "nomad_client_allocated_memory{host=\"metrics-1\"}*(1024*1024)",
     "legendFormat": "allocated"
    },
    {
     "expr": "sum(nomad_client_allocs_memory_usage{host=\"metrics-1\"}) by (instance)",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Client CPU",
   "type": "graph",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nomad_client_host_cpu_total{host=\"metrics-1\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Webapp group count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nomad_nomad_job_summary_running{task_group=\"demo\"}",
     "legendFormat": "{{task_group}}"
    }
   ]
  },
  {
   "title": "Avg. connections/instance",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg((haproxy_server_current_sessions{backend=\"http_back\"}) and (haproxy_server_up{backend=\"http_back\"} == 1)) OR on() vector(0)"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "avg((haproxy_server_current_sessions{backend=\"http_back\"}) and (haproxy_server_up{backend=\"http_back\"} == 1))",
     "legendFormat": "avg"
    },
    {
     "expr": "nomad_nomad_job_summary_running{task_group=\"demo\"}",
     "legendFormat": "count"
    },
    {
     "expr": "sum((haproxy_server_current_sessions{backend=\"http_back\"}) and (haproxy_server_up{backend=\"http_back\"} == 1))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "HAProxy Mem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"traefik\",task=\"traefik\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"traefik\",task=\"traefik\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "HAProxy Prometheus Mem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"haproxy\",task=\"haproxy_prometheus\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"haproxy\",task=\"haproxy_prometheus\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Webapp Mem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"demo\",task=\"webapp\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"demo\",task=\"webapp\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Toxiproxy Mem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"demo\",task=\"toxiproxy\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"demo\",task=\"toxiproxy\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Prometheus Mem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"prometheus\",task=\"prometheus\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"prometheus\",task=\"prometheus\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Grafana Mem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"grafana\",task=\"grafana\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"grafana\",task=\"grafana\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Loki Mem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"loki\",task=\"loki\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"loki\",task=\"loki\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Promtail Mem",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max(sum(nomad_client_allocs_memory_allocated{task_group=\"autoscaler\",task=\"promtail\"}) by (alloc_id))",
     "legendFormat": "limit"
    },
    {
     "expr": "max(sum(nomad_client_allocs_memory_usage{task_group=\"autoscaler\",task=\"promtail\"}) by (alloc_id))",
     "legendFormat": "usage"
    }
   ]
  }
 ]
}