- name: add hascicorp repo
  become: true
  shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  when: "'consul' not in ansible_facts.packages"

- name: install consul
  vars:
    consul_version: "1.10.3-1"
  become: true
  when: "'consul' not in ansible_facts.packages or consul_version not in ansible_facts.packages['consul']|map(attribute='version')|list"
  yum:
    update_cache: yes
    state: present
    name:
      - consul-{{consul_version}}

- name: consul hcl
  notify: Restart consul
  become: true
  template:
    src: templates/{{consul_hcl}}.hcl.j2
    dest: /etc/consul.d/consul.hcl