- name: add hascicorp repo
  become: true
  shell: sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  when: "'consul' not in ansible_facts.packages"

- name: install consul
#  vars:
#    consul_version: "1.10.3-1"
  become: true
  when: "'consul' not in ansible_facts.packages or consul_version not in ansible_facts.packages['consul']|map(attribute='version')|list"
  dnf:
    update_cache: yes
    state: present
    name:
#      - consul-{{consul_version}}
      - consul
      - dnsmasq

- name: consul hcl
  notify: Restart consul
  become: true
  template:
    src: templates/{{consul_hcl}}.hcl.j2
    dest: /etc/consul.d/consul.hcl

- name: consul env
  notify: Restart consul
  become: true
  copy:
    src: templates/consul.env
    dest: /etc/consul.d/consul.env
    attributes: +i

- name: config dnsmasq 10-consul
  notify: Restart dnsmasq
  copy:
    src: templates/10-consul
    dest: /etc/dnsmasq.d/10-consul

- name: change ifcfg-eth0
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^DNS1=', line: 'DNS1="127.0.0.1"' }
    - { regexp: '^DNS2=', line: 'DNS2="{{ inventory_hostname }}"' }

- name: update resolv.conf
  template:
    src: templates/resolv.conf
    dest: /etc/resolv.conf
  