---
- name: general
  hosts: all
  become: true
  roles:
    - base
    - consul

- name: docker
  hosts: worker, proxy, devops, db
  become: true
  roles:
    - docker

- name: nomad
  hosts: nomad-server, worker, db
  become: true
  roles:
    - nomad

- name: cni-plugins
  hosts: worker, db
  become: true
  roles:
    - cni-plugins

- name: install traefik
  hosts: proxy
  become: true
  roles:
    - traefik

- name: deploy jobs
  hosts: nomad-server[0]
  become: true
  roles:
    - nomad-jobs
