---
- name: general
  hosts: all
  become: true
  roles:
    - base
    - consul

- name: worker
  hosts: worker, proxy
  become: true
  roles:
    - docker

- name: nomad
  hosts: nomad-server, worker
  become: true
  roles:
    - nomad

- name: install traefik
  hosts: proxy
  become: true
  roles:
    - traefik

- name: deploy jobs
  hosts: nomad-server[0]
  become: true
  roles:
    - nomad-jobs
