Vagrant.configure("2") do |config|
  config.vm.box = "rockylinux/8"
  config.vm.box_version = "4.0.0"
  config.vm.provision "shell", inline: <<-EOF
    sudo dnf update -y
    sudo dnf install -y epel-release python36 python3-dnf
    
    sudo dd if=/dev/zero of=/EMPTY bs=1M
    sudo rm -f /EMPTY
    cat /dev/null > ~/.bash_history && history -c
  EOF
end
  
# sudo alternatives --set python /usr/bin/python3