- name: install consul
  become: true
  package:
    state: present
    name:
      - "{{consul_lib}}"

- name: consul hcl
  notify: Restart consul
  become: true
  template:
    src: templates/{{consul_hcl}}.hcl.j2
    dest: /etc/consul.d/consul.hcl

- name: create /etc/systemd/resolved.conf.d
  become: true
  file:
    path: "/etc/systemd/resolved.conf.d"
    state: directory

- name: systemd-resolved conf files
  notify: Restart systemd-resolved
  become: true
  copy:
    src: files/{{ item }}.conf
    dest: /etc/systemd/resolved.conf.d/{{ item }}.conf
  with_items:
    - docker
    - consul
