---
- name: Restart consul
  systemd:
    name: consul
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
    daemon_reload: yes
    enabled: yes