---
consul_version: "1.10.3-1"
consul_server_cluster: "{{ query('inventory_hostnames', 'consul-server:!www') | replace(\"'\", '%') }}"
consul_server_cluster_length: "{{ query('inventory_hostnames', 'consul-server:!www')|length }}"
