---
- name: add hascicorp repo
  become: true
  shell: sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
  when: "'nomad' not in ansible_facts.packages"

- name: install nomad
  become: true
#  when: "'nomad' not in ansible_facts.packages or nomad_version not in ansible_facts.packages['nomad']|map(attribute='version')|list"
  when: "'nomad' not in ansible_facts.packages"
  dnf:
    update_cache: yes
    state: present
    name:
#      - nomad-{{nomad_version}}
      - nomad

- name: nomad hcl
  notify: Restart nomad
  become: true
  template:
    src: templates/{{nomad_hcl}}.hcl.j2
    dest: /etc/nomad.d/nomad.hcl

- name: grafana dashboard
  become: true
  file:
    path: /opt/grafana/data/dashboards
    state: directory
    mode: 0777

- name: grafana dashboard
  become: true
  copy:
    src: templates/grafana-dashboard.json
    dest: /opt/grafana/data/dashboards/dashboard.json