---
- name: install docker
  become: true
  notify: Restart docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Create directory /etc/docker
  file: 
    path: /etc/docker
    state: directory
    mode: 0777
    
- name: docker daemon.json
  notify: Restart docker
  become: true
  template:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

- name: docker compose
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 0777