---
- name: consul_server
  hosts: consul_server
  become: true
  roles:
    - base
    - consul

- name: nomad_server
  hosts: nomad_server
  become: true
  roles:
    - base
    - consul
    - nomad

- name: worker
  hosts: worker
  become: true
  roles:
    - base
    - docker
    - consul
    - nomad
    - cni_plugins

# - name: general
#   hosts: all
#   become: true
#   roles:
#     - base

# - name: consul
#   hosts: consul_server, nomad_server, worker
#   become: true
#   roles:
#     - consul

# - name: docker
#   hosts: worker
#   become: true
#   roles:
#     - docker

# - name: nomad
#   hosts: nomad_server, worker
#   become: true
#   roles:
#     - nomad

# - name: cni-plugins
#   hosts: worker, db
#   become: true
#   roles:
#     - cni-plugins

# - name: install traefik
#   hosts: proxy
#   become: true
#   roles:
#     - traefik

# - name: deploy jobs
#   hosts: nomad-server[0]
#   become: true
#   roles:
#     - nomad-jobs
