---
- name: consul_server
  hosts: consul_server
  become: true
  roles:
    - base
    - consul

- name: nomad_server
  hosts: nomad_server
  become: true
  roles:
    - base
    - consul
    - nomad

- name: worker
  hosts: worker
  become: true
  roles:
    - base
    - docker
    - consul
    - nomad
    - cni_plugins

- name: proxy
  hosts: proxy
  become: true
  roles:
    - base
    - docker
    - proxy