


all:

  children:
    consul_server:
      vars:
        consul_hcl: server
      hosts:
        192.168.56.101:





; [all:vars]
; #ansible_python_interpreter=/usr/bin/python
; #ansible_user=vagrant
; #ansible_ssh_pass=vagrant

; consul_lib = consul-1.12.8-1
; nomad_lib = nomad-1.3.8-1

; consul_hcl = client
; nomad_hcl = client
; datacenter = dc1
; host_volumes = []
; metas = [{"name":"server-type", "value":"app"}]

; [consul_server:vars]
; consul_hcl = server
; [consul_server:children]
; consul_server_dc1
; [consul_server:children]
; [consul_server_dc1]
; 192.168.56.101

; # 192.168.56.102
; # 192.168.56.103

; [nomad_server:vars]
; nomad_hcl = server

; [nomad_server]
; 192.168.56.111
; # 192.168.56.112
; # 192.168.56.113

; [worker]
; 192.168.56.121
; # 192.168.56.122
; # 192.168.56.123

; # 192.168.100.181 metas='[{"name":"server-type", "value":"proxy"}]'
; # 192.168.100.191 metas='[{"name":"server-type", "value":"db-main"}]'
; # 192.168.100.192 metas='[{"name":"server-type", "value":"db-replica"}]'
; # 192.168.100.201 metas='[{"name":"server-type", "value":"metrics"}]' host_volumes='[{"name":"grafana-data", "path":"/opt/grafana/data"}]'
