---
all:
  vars:
    consul_lib: consul=*1.10.3*
    nomad_lib: nomad=*1.1.6*
    consul_hcl: client
    nomad_hcl: client
    datacenter: dc1
    nomad_network_interface: enp0s8
    host_volumes: []
    metas: [{"name":"server-type", "value":"app"}]

  children:

    consul_server:
      vars:
        consul_hcl: server
      children:
        consul_server_dc1:
          vars:
            datacenter: dc1
            hostname: consul-server
          hosts:
            192.168.56.101:
            # 192.168.56.102:
            # 192.168.56.103:
    #     consul_server_dc2:
    #       vars:
    #         datacenter: dc2
    #       hosts:
    #         192.168.56.104:
    #         192.168.56.105:
    #         192.168.56.106:

    nomad_server:
      vars:
        nomad_hcl: server
      children:
        nomad_server_dc1:
          vars:
            datacenter: dc1
            hostname: nomad-server
          hosts:
            192.168.56.111:
            # 192.168.56.112:
            # 192.168.56.113:
    #     nomad_server_dc2:
    #       vars:
    #         datacenter: dc2
    #       hosts:
    #         192.168.56.114:
    #         192.168.56.115:
    #         192.168.56.116:
    worker:
      children:
        worker_dc1:
          vars:
            datacenter: dc1
            hostname: worker
          hosts:
            192.168.56.121:
            192.168.56.122:
            192.168.56.123:
    #     worker_dc2:
    #       vars:
    #         datacenter: dc2
    #       hosts:
    #         192.168.56.124:
    #         192.168.56.125:
    #         192.168.56.126:

    proxy:
      hosts:
        192.168.56.181:
    
#  # 192.168.100.181 metas='[{"name":"server-type", "value":"proxy"}]'
#  # 192.168.100.191 metas='[{"name":"server-type", "value":"db-main"}]'
#  # 192.168.100.192 metas='[{"name":"server-type", "value":"db-replica"}]'
#  # 192.168.100.201 metas='[{"name":"server-type", "value":"metrics"}]' host_volumes='[{"name":"grafana-data", "path":"/opt/grafana/data"}]'
