---
- name: getting package facts
  package_facts:
    manager: auto

- name: add docker repo
  become: true
  shell: dnf remove -y docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-selinux docker-engine-selinux docker-engine && sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
#  when: "'docker-ce' not in ansible_facts.packages or docker_version not in ansible_facts.packages['docker-ce']|map(attribute='version')|list"
  when: "'docker-ce' not in ansible_facts.packages"

- name: install docker
  become: true
  notify: Restart docker
  yum:
    name:
#      - docker-ce-{{docker_version}}
#      - docker-ce-cli-{{docker_version}}
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Create directory /etc/docker
  file: 
    path: /etc/docker
    state: directory
    mode: 0777
    
- name: docker daemon.json
  notify: Restart docker
  become: true
  template:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

- name: docker compose
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/bin/docker-compose
    mode: 0777