[entryPoints]
  [entryPoints.traefik]
    address = ":8081"
  [entryPoints.http]
    address = ":80"

[api]
  dashboard = true
  insecure  = true

# Enable Consul Catalog configuration backend.
[providers.consulCatalog]
  refreshInterval = "1s"
  prefix           = "traefik"
  exposedByDefault = false
  defaultRule = "Host(`{{"{{ .Name }}"}}.service.consul`) || PathPrefix(`/{{"{{ .Name }}"}}`)"

  [providers.consulCatalog.endpoint]
    address = "{{ inventory_hostname }}:8500"
    scheme  = "http"

[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]

[accessLog]