- name: getting package facts
  package_facts:
    manager: auto

- name: epel release
  become: true
  yum:
    name:
      - epel-release

#- name: upgrade all packages
#  yum:
#    name: '*'
#    state: latest

- name: libs
  become: true
  yum:
    update_cache: yes
    state: present
    name:
      - yum-utils
      - htop
      - curl
      - nano
      - bind-utils

- name: update vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.conf