---
- name: dir /opt/varnish
  become: true
  file:
    path: "/opt/varnish"
    state: directory

- name: copy default.vcl
  notify: Restart varnish
  become: true
  template:
    src: files/{{ item }}.j2
    dest: /opt/varnish/{{ item }}
  with_items:
    - default.vcl
    - docker-compose.yml

- name: update bridge-nf-call-iptable
  sysctl:
    name: net.ipv4.ip_unprivileged_port_start
    value: "79"
    state: present
    reload: yes
    sysctl_file: /etc/sysctl.conf
